[package]
name = "copters"
version = "0.1.0"
edition = "2024"
authors = ["Avinash Madavan <avinash.madavan@gmail.com>"]
description = "A Rust library for numerical optimization."
license = "MIT"
repository = "https://github.com/amadavan/copters"
keywords = ["optimization", "linear-programming", "solver", "rust"]
categories = ["science", "algorithms", "mathematics"]
license-file = "LICENSE"
readme = "README.md"

[dependencies]
dyn-clone = "1.0.20"
faer = "0.23.2"

[dev-dependencies]
divan = "0.1.21"
